- maruoka.html
> maruokatest

- app/Mail/UserDelRes.php
- app/Mail/UserFinAddRes.php
- app/Mail/UserFinRes.php
- app/Models/Reservation.php
以下バックログの対応を行いました。
バックログ：
https://ts-pj.backlog.com/view/SMG-196
> ユーザー側の備考修正

- public/css/template.css
- public/js/edit_luggage_date.js
- resources/views/user/reservations/check.blade.php
- resources/views/user/reservations/create.blade.php
- resources/views/user/reservations/destroy_check.blade.php
- resources/views/user/reservations/re_create.blade.php
以下対応を行いました。
※一部不要なソースがあったため、削除しました。
バックログ：
https://ts-pj.backlog.com/view/SMG-194
> ユーザー箇所のみ曜日の表示対応

- app/Mail/UserFinPreRes.php
メールの変数修正対応を行いました。
バックログ：
https://ts-pj.backlog.com/view/SMG-201
> 【2】-1｜自動返信メールの不具合修正

- public/css/template.css
- public/js/edit_luggage_date.js
- resources/views/user/pre_reservations/calculate.blade.php
- resources/views/user/pre_reservations/show.blade.php
漏れがあったため対応しました。
バックログ：
https://ts-pj.backlog.com/view/SMG-194
> 荷物預かりの曜日表示対応

- resources/views/admin/reservations/calculate.blade.php
以下対応を行いました。
バックログ：
https://ts-pj.backlog.com/view/SMG-203
> シークレットモードの請求内訳計算修正

- app/Http/Controllers/Admin/MultiplesController.php
- app/Http/Controllers/Admin/PreReservationsController.php
- app/Mail/UserCxlChck.php
- app/Mail/UserFinCxl.php
- app/Mail/UserFinRes.php
- app/Mail/UserPreResCxl.php
以下対応を行いました。
バックログ：
https://ts-pj.backlog.com/view/SMG-206
> 自動返信メールの変数修正

- config/app.php
> 管理者用メールアドアレス変更

- resources/views/admin/multiples/agent_edit.blade.php
- resources/views/admin/multiples/edit.blade.php
バックログ：
https://ts-pj.backlog.com/view/SMG-210
> SMG-210：一括仮押さえのイベント開始・終了時間修正

- app/Http/Controllers/Admin/AgentsReservationsController.php
- app/Http/Controllers/Admin/ReservationsController.php
- resources/views/admin/agents_reservations/edit_calc.blade.php
バックログ：
https://ts-pj.backlog.com/view/SMG-209
一部値が保持できていない項目がありますが、
「再計算する」ボタンを押下したときと同様の値が保持されるよう対応しています。
保持されない値↓
　・料金体系がない場合の手打ちの会場料
　・料金体系がある場合に表示される会場料の割引額
> SMG-209：予約編集可能項目の値保持

- app/Http/Controllers/User/Auth/RegisterController.php
バックログ：
https://ts-pj.backlog.com/view/SMG-212
> SMG-212：ユーザー会員登録　支払い期日デフォルト変更対応

- app/Models/Venue.php
バックログ：
https://ts-pj.backlog.com/view/SMG-214
> SMG-214 夜間枠＋延長料金(17:00、17:30～23:00)の計算後の内訳が「会場料金●●円」となって延長料金が表示されない

- app/Models/MultipleReserve.php
- app/Models/PreReservation.php
- app/Models/Reservation.php
- app/Models/User.php
https://ts-pj.backlog.com/view/SMG-161#comment-291784632
上記指摘より、ID検索は前方一致となるよう変更しました。
> SMG-161 一括仮押さえ一覧の一括仮押さえID、予約一覧の予約一括ID、売上請求一覧の予約一括IDの検索を有効にする

- resources/views/layouts/reservation/app.blade.php
https://ts-pj.backlog.com/view/SMG-65#comment-292716178
上記指摘より、パンくずを修正
> SMG-65 会員登録画面のパンくず表示を「会場予約」から「会員登録」に修正

- resources/views/admin/agents_reservations/calculate.blade.php
- resources/views/admin/agents_reservations/check.blade.php
- resources/views/admin/agents_reservations/create.blade.php
- resources/views/admin/agents_reservations/edit.blade.php
- resources/views/admin/agents_reservations/edit_calc.blade.php
- resources/views/admin/agents_reservations/edit_check.blade.php
- resources/views/admin/multiples/agent_edit.blade.php
- resources/views/admin/multiples/edit.blade.php
- resources/views/admin/pre_agent_reservations/edit.blade.php
- resources/views/admin/pre_agent_reservations/edit_calculate.blade.php
- resources/views/admin/pre_agent_reservations/single_calculate.blade.php
- resources/views/admin/pre_agent_reservations/single_check.blade.php
- resources/views/admin/pre_reservations/edit.blade.php
- resources/views/admin/pre_reservations/show.blade.php
- resources/views/admin/pre_reservations/single_calculate.blade.php
- resources/views/admin/pre_reservations/single_check.blade.php
- resources/views/admin/pre_reservations/single_re_calculate.blade.php
- resources/views/admin/reservations/calculate.blade.php
- resources/views/admin/reservations/check.blade.php
- resources/views/admin/reservations/create.blade.php
- resources/views/admin/reservations/edit.blade.php
- resources/views/admin/reservations/edit_calc.blade.php
- resources/views/admin/reservations/edit_check.blade.php
- resources/views/admin/reservations/show.blade.php
https://ts-pj.backlog.com/view/SMG-229
> SMG_229の修正

- public/js/holidays.js
- resources/views/admin/multiples/agent_edit.blade.php
- resources/views/admin/multiples/edit.blade.php
- resources/views/user/reservations/create.blade.php
- resources/views/user/reservations/re_create.blade.php
https://ts-pj.backlog.com/view/SMG-97
> SMG-97 荷物預かり：カレンダーの予約可能日の調節

- app/Http/Controllers/User/ReservationsController.php
- resources/views/user/home/index.blade.php
https://ts-pj.backlog.com/view/SMG-131
> SMG-131 顧客側（ログイン状態） 予約一覧画面 携帯で見た際の 予約一覧/過去履歴

- resources/views/admin/reservations/show.blade.php
https://ts-pj.backlog.com/view/SMG-153
> SMG-153 登録予約案件をｷｬﾝｾﾙする際の流れで表示する画面上部の注釈テキスト（リリース後対応）

- app/Mail/ResetEmail.php
- app/Mail/ResetEmailDone.php
https://ts-pj.backlog.com/view/SMG-224
> SMG-224 メールアドレス変更のご確認メールの遷移先の修正

- resources/views/admin/multiples/calculate.blade.php
- resources/views/admin/multiples/edit.blade.php
- resources/views/admin/pre_reservations/edit.blade.php
- resources/views/admin/pre_reservations/single_calculate.blade.php
- resources/views/admin/pre_reservations/single_check.blade.php
- resources/views/admin/pre_reservations/single_re_calculate.blade.php
- resources/views/user/pre_reservations/calculate.blade.php
- resources/views/user/pre_reservations/show.blade.php
https://ts-pj.backlog.com/view/SMG-233
> 仮押さえ部分の荷物預かり料の表記を削除

- public/js/admin/clients/validation.js
- resources/views/admin/clients/create.blade.php
- resources/views/admin/clients/edit.blade.php
https://ts-pj.backlog.com/view/SMG-230
> SMG-230 顧客情報の振込名に半角の入力制御の追加

- app/Http/Controllers/Admin/PreReservationsController.php
https://ts-pj.backlog.com/view/SMG-231
> SMG-231 仮押さえ一覧からの仮押さえの削除、仮押さえ詳細画面からの削除ができない

- app/Http/Controllers/Admin/MultiplesController.php
- resources/views/admin/multiples/agent_edit.blade.php
- resources/views/admin/multiples/calculate.blade.php
https://ts-pj.backlog.com/view/SMG-235
以下チャットワークでのやり取り
https://www.chatwork.com/#!rid194495194-1755894133332901888
> SMG-235 一括仮押さえのコピー元に値を保持させる
